<?php
if( function_exists('acf_add_local_field_group') ):
  acf_add_options_page('Slideroptionen');
  acf_add_options_page('Home Video');

  acf_add_local_field_group(array (
  	'key' => 'group_58a8910b1a6fd',
  	'title' => 'Home Seite',
  	'fields' => array (
  		array (
  			'key' => 'field_58a8911b7985b',
  			'label' => 'Slider oder Video',
  			'name' => 'slider_oder_video',
  			'type' => 'select',
  			'instructions' => 'Wählen sie eine Option aus. Bitte beachte, dass du beim Video ein korrektes Format hochladen musst (.mp4 empfohlen)',
  			'required' => 1,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'choices' => array (
  				'none' => 'Keins',
  				'slider' => 'Bilderslider',
  				'video' => 'Video',
  			),
  			'default_value' => array (
  				'none' => 'none',
  			),
  			'allow_null' => 0,
  			'multiple' => 0,
  			'ui' => 1,
  			'ajax' => 0,
  			'placeholder' => '',
  			'disabled' => 0,
  			'readonly' => 0,
  		),
  	),
  	'location' => array (
  		array (
  			array (
  				'param' => 'page_template',
  				'operator' => '==',
  				'value' => 'template-home.php',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'default',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 1,
  	'description' => '',
  ));

  acf_add_local_field_group(array (
  	'key' => 'group_58a89b7a1d542',
  	'title' => 'Mitarbeiter',
  	'fields' => array (
  		array (
  			'key' => 'field_58a89b7fb0b41',
  			'label' => 'Vorname',
  			'name' => 'vorname',
  			'type' => 'text',
  			'instructions' => '',
  			'required' => 1,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'default_value' => '',
  			'placeholder' => '',
  			'prepend' => '',
  			'append' => '',
  			'maxlength' => '',
  			'readonly' => 0,
  			'disabled' => 0,
  		),
  		array (
  			'key' => 'field_58a89b88b0b42',
  			'label' => 'Name',
  			'name' => 'name',
  			'type' => 'text',
  			'instructions' => '',
  			'required' => 1,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'default_value' => '',
  			'placeholder' => '',
  			'prepend' => '',
  			'append' => '',
  			'maxlength' => '',
  			'readonly' => 0,
  			'disabled' => 0,
  		),
  		array (
  			'key' => 'field_58a89b91b0b43',
  			'label' => 'Bild',
  			'name' => 'bild',
  			'type' => 'image',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'return_format' => 'array',
  			'preview_size' => 'thumbnail',
  			'library' => 'all',
  			'min_width' => '',
  			'min_height' => '',
  			'min_size' => '',
  			'max_width' => '',
  			'max_height' => '',
  			'max_size' => '',
  			'mime_types' => '',
  		),
  	),
  	'location' => array (
  		array (
  			array (
  				'param' => 'post_type',
  				'operator' => '==',
  				'value' => 'users',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'default',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 1,
  	'description' => '',
  ));

  acf_add_local_field_group(array (
  	'key' => 'group_58aa02f7f0e1e',
  	'title' => 'Produkte',
  	'fields' => array (
  		array (
  			'key' => 'field_58aa030b9eb7d',
  			'label' => 'Produktbild',
  			'name' => 'produktbild',
  			'type' => 'image',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'return_format' => 'array',
  			'preview_size' => 'thumbnail',
  			'library' => 'all',
  			'min_width' => '',
  			'min_height' => '',
  			'min_size' => '',
  			'max_width' => '',
  			'max_height' => '',
  			'max_size' => '',
  			'mime_types' => '',
  		),
  		array (
  			'key' => 'field_58aa03199eb7e',
  			'label' => 'Produktbeschreibung',
  			'name' => 'produktbeschreibung',
  			'type' => 'wysiwyg',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'default_value' => '',
  			'tabs' => 'all',
  			'toolbar' => 'basic',
  			'media_upload' => 1,
  		),
  		array (
  			'key' => 'field_58aa03319eb7f',
  			'label' => 'Produktpreis',
  			'name' => 'produktpreis',
  			'type' => 'number',
  			'instructions' => '',
  			'required' => 1,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'default_value' => '',
  			'placeholder' => '',
  			'prepend' => 'CHF',
  			'append' => '',
  			'min' => '',
  			'max' => '',
  			'step' => '',
  			'readonly' => 0,
  			'disabled' => 0,
  		),
  	),
  	'location' => array (
  		array (
  			array (
  				'param' => 'post_type',
  				'operator' => '==',
  				'value' => 'products',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'default',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 1,
  	'description' => '',
  ));

  acf_add_local_field_group(array (
  	'key' => 'group_58a89d5643e9d',
  	'title' => 'Slider',
  	'fields' => array (
  		array (
  			'key' => 'field_58a89db296087',
  			'label' => 'Slidereffekt',
  			'name' => 'slidereffekt',
  			'type' => 'select',
  			'instructions' => 'Wähle einen Slidereffekt aus',
  			'required' => 1,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'choices' => array (
  				'normal' => 'Normal',
  				'fade' => 'Fade Effekt',
  				'cube' => '3D Cube Effekt',
  				'coverflow' => '3D Coverflow,',
  				'flip' => '3D Flip Effect',
  			),
  			'default_value' => array (
  				'normal' => 'normal',
  			),
  			'allow_null' => 0,
  			'multiple' => 0,
  			'ui' => 0,
  			'ajax' => 0,
  			'placeholder' => '',
  			'disabled' => 0,
  			'readonly' => 0,
  		),
  		array (
  			'key' => 'field_58a89d5a96084',
  			'label' => 'Sliderbilder',
  			'name' => 'sliderbilder',
  			'type' => 'repeater',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'min' => '',
  			'max' => '',
  			'layout' => 'table',
  			'button_label' => 'Bild hinzufügen',
  			'sub_fields' => array (
  				array (
  					'key' => 'field_58a89d8096085',
  					'label' => 'Bild',
  					'name' => 'bild',
  					'type' => 'image',
  					'instructions' => '',
  					'required' => 1,
  					'conditional_logic' => 0,
  					'wrapper' => array (
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'return_format' => 'array',
  					'preview_size' => 'thumbnail',
  					'library' => 'all',
  					'min_width' => '',
  					'min_height' => '',
  					'min_size' => '',
  					'max_width' => '',
  					'max_height' => '',
  					'max_size' => '',
  					'mime_types' => '',
  				),
  				array (
  					'key' => 'field_58a89d9296086',
  					'label' => 'Bildbeschreibung',
  					'name' => 'bildbeschreibung',
  					'type' => 'text',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array (
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'default_value' => '',
  					'placeholder' => '',
  					'prepend' => '',
  					'append' => '',
  					'maxlength' => '',
  					'readonly' => 0,
  					'disabled' => 0,
  				),
  			),
  		),
  	),
  	'location' => array (
  		array (
  			array (
  				'param' => 'options_page',
  				'operator' => '==',
  				'value' => 'acf-options-slideroptionen',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'default',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 1,
  	'description' => '',
  ));

  acf_add_local_field_group(array (
  	'key' => 'group_58aa0e1fbe0c7',
  	'title' => 'Tagesmenü',
  	'fields' => array (
  		array (
  			'key' => 'field_58aa0e2968aca',
  			'label' => 'Bild',
  			'name' => 'bild',
  			'type' => 'image',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'return_format' => 'array',
  			'preview_size' => 'thumbnail',
  			'library' => 'all',
  			'min_width' => '',
  			'min_height' => '',
  			'min_size' => '',
  			'max_width' => '',
  			'max_height' => '',
  			'max_size' => '',
  			'mime_types' => '',
  		),
  		array (
  			'key' => 'field_58aa198909ee1',
  			'label' => 'Kurzbeschreibung',
  			'name' => 'kurzbeschreibung',
  			'type' => 'textarea',
  			'instructions' => '',
  			'required' => 1,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'default_value' => '',
  			'placeholder' => '',
  			'maxlength' => '',
  			'rows' => '',
  			'new_lines' => 'wpautop',
  			'readonly' => 0,
  			'disabled' => 0,
  		),
  		array (
  			'key' => 'field_58aa0e3468acb',
  			'label' => 'Beschreibung',
  			'name' => 'beschreibung',
  			'type' => 'wysiwyg',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'default_value' => '',
  			'tabs' => 'all',
  			'toolbar' => 'full',
  			'media_upload' => 1,
  		),
  	),
  	'location' => array (
  		array (
  			array (
  				'param' => 'post_type',
  				'operator' => '==',
  				'value' => 'tagesmenu',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'default',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 1,
  	'description' => '',
  ));

  acf_add_local_field_group(array (
  	'key' => 'group_58a89486acaf8',
  	'title' => 'Top Slider',
  	'fields' => array (
  		array (
  			'key' => 'field_58a8948f81b0f',
  			'label' => 'Slider anzeigen',
  			'name' => 'slider_anzeigen',
  			'type' => 'checkbox',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'choices' => array (
  				'yes' => 'Ja',
  			),
  			'default_value' => array (
  			),
  			'layout' => 'vertical',
  			'toggle' => 0,
  		),
  	),
  	'location' => array (
  		array (
  			array (
  				'param' => 'post_type',
  				'operator' => '==',
  				'value' => 'page',
  			),
  			array (
  				'param' => 'page_template',
  				'operator' => '!=',
  				'value' => 'template-home.php',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'default',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 1,
  	'description' => '',
  ));

  acf_add_local_field_group(array (
  	'key' => 'group_58a89ea116856',
  	'title' => 'Video',
  	'fields' => array (
  		array (
  			'key' => 'field_58a89ea5d98b3',
  			'label' => 'Video',
  			'name' => 'homevideo',
  			'type' => 'file',
  			'instructions' => 'Geeignetes Format: .mp4',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array (
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'return_format' => 'array',
  			'library' => 'all',
  			'min_size' => '',
  			'max_size' => '',
  			'mime_types' => '',
  		),
  	),
  	'location' => array (
  		array (
  			array (
  				'param' => 'options_page',
  				'operator' => '==',
  				'value' => 'acf-options-home-video',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'default',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 1,
  	'description' => '',
  ));
endif;
